# Generated by Django 2.1.4 on 2019-02-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MathPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'MathPoint',
            },
        ),
        migrations.CreateModel(
            name='MathProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('ques', models.TextField()),
                ('ques_type', models.TextField()),
                ('answer', models.TextField()),
                ('ques_points', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'MathProblem',
            },
        ),
    ]
