# Generated by Django 2.1.4 on 2019-02-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RigntQues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuId', models.CharField(max_length=8)),
                ('quesId', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'RightQues',
            },
        ),
        migrations.AlterField(
            model_name='wrongques',
            name='quesId',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='wrongques',
            name='stuId',
            field=models.CharField(max_length=8),
        ),
    ]
