# Generated by Django 2.1.4 on 2019-02-09 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_auto_20190209_1123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RigntQues',
            new_name='RightQues',
        ),
    ]
