# Generated by Django 2.1.4 on 2019-02-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.CharField(choices=[('1班', '1班'), ('1班', '2班'), ('1班', '3班'), ('1班', '4班')], default='1班', max_length=32),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=32),
        ),
    ]
